### ISSUE TITLE
The section on Binding Table needs to be aligned with best practice. 

### ISSUE THREAD

**Issue by mjkoster** [core-wg/dynlink#12]

**Comment by bsilverajan** [comment]
I created pull request  #13 with a rewrite of this section. Please review it and see if that fits what we wanted to do for the Binding Table. 

_**The amendments in the pull request text are copy-pasted below:**_

5.  Binding Table

   The Binding Table is a special resource that describes the bindings
   on an endpoint.  An endpoint offering a representation of the Binding
   Table resource SHOULD indicate its presence and enable its discovery
   by advertising a link at "/.well-known/core" [RFC6690].  If so, the
   Binding Table resource MUST be discoverable by using the Resource
   Type (rt) 'core.bnd'.

   The Methods column defines the REST methods supported by the Binding
   Table, which are described in more detail below.
         +---------------+----------+----------+----------------+
         | Resource          | rt=            | Methods  | Content-Format |
         +---------------+----------+----------+----------------+
         | Binding Table | core.bnd    | GET, PUT | link-format         |
         +---------------+----------+----------+----------------+

                    Table 4: Binding Table Description

   The REST methods GET and PUT are used to manipulate a Binding Table.
   A GET request simply returns the current state of a Binding Table.  A
   request with a PUT method and a content format of application/link-
   format is used to clear the bindings to the table or replaces its
   entire contents.  All links in the payload of a PUT rquest MUST have
   a relation type "boundto".

   (Editor's Note: Usage of the PATCH method for fine-grained addition
   and removal of individual bindings is under study.)

   The following example shows requests for discovering, retrieving and
   replacing bindings in a binding table.

   Req: GET /.well-known/core?rt=core.bnd (application/link-format)
   Res: 2.05 Content (application/link-format)
   </bnd/>;rt=core.bnd;ct=40

   Req: GET /bnd/
   Res: 2.05 Content (application/link-format)
   <coap://sensor.example.com/a/switch1/>;
           rel=boundto;bind=obs;anchor=/a/fan,;bind="obs",
   <coap://sensor.example.com/a/switch2/>;
           rel=boundto;bind=obs;anchor=/a/light;bind="obs"

   Req: PUT /bnd/ (Content-Format: application/link-format)
   <coap://sensor.example.com/s/light>;
     rel="boundto";anchor="/a/light";bind="obs";pmin="10";pmax="60"
   Res: 2.04 Changed

   Req: GET /bnd/
   Res: 2.05 Content (application/link-format)
   <coap://sensor.example.com/s/light>;
     rel="boundto";anchor="/a/light";bind="obs";pmin="10";pmax="60"

                      Figure 2: Binding Table Example



8.  IANA Considerations

8.1.  Resource Type value 'core.bnd'

   This specification registers a new Resource Type Link Target
   Attribute 'core.bnd' in the Resource Type (rt=) registry established
   as per [RFC6690].

   Attribute Value:  core.bnd

   Description: See Section 5.  This attribute value is used to discover
   the resource representing a binding table, which describes the link
   bindings between source and destination resources for the purposes of
   synchronizing their content.

   Reference: This specification.  Note to RFC editor: please insert the
   RFC of this specification.

   Notes: None

**Comment by bsilverajan** [comment]
Merging after email discussion with @mjkoster
