### ISSUE TITLE
Binding attributes values for greater than and less than conflict with LwM2M

### ISSUE THREAD

**Issue by tcareynokia** [core-wg/dynlink#4]
The 'gth' and 'lth' values used for Binding Attributes were originally 'gt' and 'lt' in drafts previous to version 3. The attributes are used by LwM2M with the original values of 'gt' and 'lt'. We should revert to using the values 'gt' and 'lt' as those specifications have been published for a couple of years now.

**Comment by bsilverajan** [comment]
@tcareynokia agreed. I'm going to be this document's editor, and a call with the authors confirmed we'll revert "gth" and "lth" for the next draft. We'll also confirm this is ok with the OMA for future versions of the draft.
